// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.java.netty.google;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.java.netty.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.java.netty.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.java.netty.google.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .com.java.netty.proto.StudentResponse studentResponse = 1;</code>
   */
  com.java.netty.google.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.java.netty.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.java.netty.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.java.netty.google.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.java.netty.proto.StudentResponse studentResponse = 1;</code>
   */
  com.java.netty.google.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
