server:
  port: 8083
  address: 127.0.0.1
  servlet:
    context-path: /spring-boot

linux:
  myport: 192.168.26.20

spring:
  profiles:
    active: boot # 激活配置文件
    #    include: boot,druid1 或者 ProtertyConfigure 类中激活配置文件
    include: druid4,redis # 或者 ProtertyConfigure 类中激活配置文件 druid3 配置无效，数据源有效
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    read-size: 2 # 从数据库个数

# 自定义属性
com:
  xwz:
    sample: 我们
    # 直接引用属性值
    desc: ${com.xwz.sample}
    # 使用随机数
    value: ${random.value}