spring:
  datasource:
    url: jdbc:mysql://${linux.myport}:3306/property?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 158262751
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 30                           #初始化连接池的连接数量 大小，最小，最大
      min-idle: 5
      initial-size: 10
      ## 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
        session-stat-max-count: 100000
        principal-session-name: admin
        principal-cookie-name: admin
        profile-enable: true

      #基础监控配置（主要是配置监控的身份验证信息，毕竟系统运行状态也是个小秘密）
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #禁止手动重置监控数据
        reset-enable: true #false
        login-username: admin
        login-password: 123456
        allow:
        deny: 192.168.13.14

      filter:
        wall:
          enabled: true
          db-type: mysql
          config:
            alter-table-allow: false
            truncate-allow: false
            drop-table-allow: false
            none-base-statement-allow: false
            update-where-none-check: true
            metadata-allow: true
          log-violation: true
          throw-exception: true
      #Spring监控，对内部各接口调用的监控
      aop-patterns: com.xwz.boot.controller.*,com.xwz.boot.mapper.*,com.xwz.boot.service.*
      # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis: 500'
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙  配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      # ！！！请勿配置timeBetweenLogStatsMillis 会定时输出日志 并导致统计的sql清零
#      time-between-log-stats-millis: 20000
    filters: stat,wall

