server:
  port: 8082

# 日志文件配置,用之前需要排除 logback 的依赖
logging:
  level:
    com.xwz.boot.mapper: debug
  config: classpath:log4j/log4j2.yml

mybatis-plus:
  #配置包扫描位置
  configuration:
    #适配驼峰命名法
    map-underscore-to-camel-case: true #默认为true
  #    interceptors: com.xwz.boot.configure.MybatisInterceptor 失败
  type-aliases-package: com.xwz.boot.model
  mapper-locations: classpath:com/xwz/boot/mapper/*.xml
