cluster.name: myapp
node.name: node1
network.bind_host: 0.0.0.0
network.publish_host: 192.168.150.21
http.port: 9200
transport.tcp.port: 9300
http.cors.enabled: true
http.cors.allow-origin: "*"
node.master: true
node.data: true
http.enabled: true
discovery.zen.minimum_master_nodes: 1
