cluster.name: myapp
node.name: node2
network.bind_host: 0.0.0.0
network.publish_host: 192.168.150.21
http.port: 9201
transport.tcp.port: 9301
http.cors.enabled: true
http.cors.allow-origin: "*"
node.master: true
node.data: true
http.enabled: true
discovery.zen.minimum_master_nodes: 2
